### ISSUE TITLE
Add u/Automoderator to a white-list

### ISSUE THREAD

**Issue by RegExrTech** [Tjstretchalot/USLBot-Site#3]
Today, r/slavelabor banned u/automoderator via the USL. This was eventually fixed, but automod is an integral part of any subreddit subscribed to the USL. Removing the ability to use automod is a power that no individual should have. 

If there is a way to sanity check incoming bans and make sure no one is trying to ban automod, that would be very helpful.

**Comment by Tjstretchalot** [comment]
Ahh; will add protection for /u/Automoderator. Recreating this issue at the appropriate spot: https://github.com/Tjstretchalot/USLBot/issues/11
